name: Convention update
description: Konvensiya/standart yenilənməsi
labels: [convention]
body:
  - type: textarea
    id: context
    attributes:
      label: Kontekst
      placeholder: Mövcud qayda və problem
    validations:
      required: true
  - type: textarea
    id: change
    attributes:
      label: Dəyişiklik
      placeholder: Yeni təklif olunan forma
    validations:
      required: true
