name: Policy change
description: Siyasət dəyişiklik təklifi
labels: [policy]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivasiya
      placeholder: Niyə lazımdır?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Təsir dairəsi
      placeholder: Kimlərə/hansılara təsir edir?
  - type: textarea
    id: proposal
    attributes:
      label: Təklif
      placeholder: Dəyişiklik mətni və ya link
    validations:
      required: true
